### ISSUE TITLE
Unable to download the book "Error: error 0 error"

### ISSUE THREAD

**Issue by kishorepillai** [pmem/book#27]
Using firefox, I tried to download the pmemory  free ebook. but unable to proceed  due to the error "Error: error 0 error"

**Comment by sscargal** [comment]
Sorry about that. Occasionally there may be an issue on the back end. Please wait a few mins and try again. If that doesn't work, try disabling any Ad Blocker or Virus Protection that scans websites. We have found several of these plugins block the javascript that runs on this page, resulting in form submission errors. If none of this works, contact us on the #pmem Slack Channel or the PMem Forum.

Alternatively, download the book in eBook and PDF formats directly from [APress](https://link.springer.com/book/10.1007%2F978-1-4842-4932-1).

**Comment by kishorepillai** [comment]
Thanks @sscargal .This helps
